### ISSUE TITLE
Case-insensitive neo4j query for the VulnerabilitiesDataImport tool

### ISSUE THREAD

**Issue by ch4dbzh** [zeronetworks/BloodHound-Tools#12]
Hi !

Thanks for releasing this tool.

I identified a minor issue with the way the OpenVAS reports are being parsed by the VulnerabilitiesDataImport tool. 
It seems that OpenVAS tends to **lowercase** the hostname of the vulnerable assets (e.g. vulnerable.contoso.local) 

However, the data stored within BloodHound seems to be stored in **uppercase** (e.g. VULNERABLE.CONTOSO.LOCAL).

This results in the **VulnerabilitiesDataImport/neo4j_api.py** not being able to match the results / hosts of an OpenVAS CSV file. Indeed, neo4j queries are **case sensitive**.

I would like to suggest the use of the **toUpper** function in the **VulnerabilitiesDataImport/neo4j_api.py** file, on line **34** : 
- [https://github.com/zeronetworks/BloodHound-Tools/blob/main/VulnerabilitiesDataImport/neo4j_api.py#L34](https://github.com/zeronetworks/BloodHound-Tools/blob/main/VulnerabilitiesDataImport/neo4j_api.py#L34)

**Original**
```
            result = session.run('WITH $vulnerabilities_data AS vulnerabilities_data '
                                 'UNWIND vulnerabilities_data as vulnerability_data '
                                 'MATCH (c:Computer {name: vulnerability_data[0]}) '
                                 'SET c.is_vulnerable = TRUE, c.cves = vulnerability_data[1] '
                                 'RETURN c.name',
                                 vulnerabilities_data=vulnerabilities_data)
```

**Modified**
```
            result = session.run('WITH $vulnerabilities_data AS vulnerabilities_data '
                                 'UNWIND vulnerabilities_data as vulnerability_data '
                                 'MATCH (c:Computer {name: toUpper(vulnerability_data[0])}) '
                                 'SET c.is_vulnerable = TRUE, c.cves = vulnerability_data[1] '
                                 'RETURN c.name',
                                 vulnerabilities_data=vulnerabilities_data)
```

Have a great day !

**Comment by dekelpaz** [comment]
Thanks! 
Fixed in the ReportParser class to also make sure the vulnerabilities are grouped together correctly by hostname.
