### ISSUE TITLE
Columns (10) have mixed types. Specify dtype option on import or set low_memory=False

### ISSUE THREAD

**Issue by Linnicks** [zeronetworks/BloodHound-Tools#13]
Line 123 report_parser.py

...
return pd.read_csv(self._report_path, **kwargs)
...

Add this to resolve or I guess add argument

return pd.read_csv(self._report_path, low_memory=False, **kwargs)

**Comment by dekelpaz** [comment]
Can you please share which type of report caused this warning?

**Comment by Linnicks** [comment]
A nessus report. A vulnerability list export.

**Comment by dekelpaz** [comment]
Did you generate the report by going to My Scans > [Scan Name] > Report > Report Format: CSV > Generate Report?
![image](https://user-images.githubusercontent.com/95357879/199527261-576f0236-73cb-4d51-ab96-78ac44dfe16b.png)
