### ISSUE TITLE
Spelling mistake on home page

### ISSUE THREAD

**Issue by chiefoldmist** [zeronetworks/BloodHound-Tools#3]
Sorry, really minor point, and very pedantic, but ransomware is not spelt correctly in this sentence on the project's homepage:

"It can be used to measure a network resilience for **ransomare** infections, and identify "weak links" in the network."

**Comment by chiefoldmist** [comment]
On this page:

https://github.com/zeronetworks/BloodHound-Tools/tree/main/Ransomulator

**Comment by sagiesec** [comment]
Nice catch
